"""empty message

Revision ID: 013dc1560698
Revises: 612d46ccf614
Create Date: 2026-10-06 07:23:43.071030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013dc1560698'
down_revision: Union[str, Sequence[str], None] = '612d46ccf614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'DOUBTFUL', 'FAIL', name='verdict'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_checks_created_at'), 'quality_checks', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_checks_created_at'), table_name='quality_checks')
    op.drop_table('quality_checks')
    # ### end Alembic commands ###
