"""empty message

Revision ID: 612d46ccf614
Revises: 986fb2c2554b
Create Date: 2026-09-25 12:47:00.101356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612d46ccf614'
down_revision: Union[str, Sequence[str], None] = '986fb2c2554b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmcalls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('GENERATION', 'QUALITYCHECK', name='purpose'), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=16, scale=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llmcalls_created_at'), 'llmcalls', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llmcalls_created_at'), table_name='llmcalls')
    op.drop_table('llmcalls')
    # ### end Alembic commands ###
